# Generated by Django 6.0.4 on 2026-06-08 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Identifiant URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "submissions_open",
                    models.BooleanField(
                        default=False, verbose_name="Soumissions ouvertes"
                    ),
                ),
                (
                    "submission_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date limite de soumission"
                    ),
                ),
                (
                    "eval_visibility",
                    models.CharField(
                        choices=[
                            ("after_own", "Après dépôt de son propre avis"),
                            (
                                "after_deliberation",
                                "Après ouverture de la délibération",
                            ),
                        ],
                        default="after_own",
                        max_length=30,
                        verbose_name="Visibilité des avis",
                    ),
                ),
                (
                    "eval_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Les évaluateurs ne voient pas le nom des autres membres du comité.",
                        verbose_name="Anonymat entre évaluateurs",
                    ),
                ),
                (
                    "eval_assignment",
                    models.CharField(
                        choices=[
                            ("all", "Tout le comité évalue toutes les propositions"),
                            ("manual", "Assignation manuelle par l'organisateur"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Mode d'assignation",
                    ),
                ),
                (
                    "double_blind",
                    models.BooleanField(
                        default=False,
                        help_text="Les noms des auteurs sont masqués aux évaluateurs.",
                        verbose_name="Double-aveugle",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("organizer", "Organisateur·ice"),
                            ("committee", "Comité scientifique"),
                            ("speaker", "Intervenant·e"),
                        ],
                        default="organizer",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur·ice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "unique_together": {("user", "event")},
            },
        ),
    ]
