# Generated by Django 6.0.4 on 2026-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="submission_show_availability",
            field=models.BooleanField(
                default=False, verbose_name="Champ « Disponibilités »"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="submission_show_format",
            field=models.BooleanField(
                default=True, verbose_name="Champ « Format souhaité »"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="submission_show_keywords",
            field=models.BooleanField(default=True, verbose_name="Champ « Mots-clés »"),
        ),
    ]
