# Generated by Django 6.0.4 on 2026-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_submission_form_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="submission_instructions",
            field=models.TextField(
                blank=True, verbose_name="Instructions pour les soumissionnaires"
            ),
        ),
    ]
