# Generated by Django 6.0.4 on 2026-06-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_submission_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bibliography",
            field=models.TextField(blank=True, verbose_name="Bibliographie"),
        ),
        migrations.AddField(
            model_name="event",
            name="call_for_papers",
            field=models.TextField(blank=True, verbose_name="Appel à communications"),
        ),
    ]
