# Generated by Django 6.0.4 on 2026-06-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_public_page_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Affiché en haut de la page publique. Recommandé : 1200 × 400 px.",
                null=True,
                upload_to="events/banners/",
                verbose_name="Visuel",
            ),
        ),
    ]
