# Generated by Django 6.0.4 on 2026-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_keydate_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="primary_color",
            field=models.CharField(
                blank=True,
                help_text="Code hexadécimal, ex. #1e3a5f. Laisser vide pour la couleur par défaut.",
                max_length=7,
                verbose_name="Couleur principale",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="site_footer",
            field=models.CharField(
                blank=True,
                help_text="Texte affiché en bas de chaque page. Ex. : « Organisé par l'Univ. de Lyon ».",
                max_length=200,
                verbose_name="Pied de page",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Court texte affiché sous le nom de l'événement sur la page publique.",
                max_length=200,
                verbose_name="Sous-titre",
            ),
        ),
    ]
