# Generated by Django 6.0.4 on 2026-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_membership_token_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_bilingual",
            field=models.BooleanField(
                default=False,
                help_text="Active les champs anglais et le sélecteur de langue sur les pages publiques.",
                verbose_name="Événement bilingue (FR/EN)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="site_footer_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Pied de page (EN)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="submission_instructions_en",
            field=models.TextField(
                blank=True, verbose_name="Instructions pour les soumissionnaires (EN)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tagline_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Sous-titre (EN)"
            ),
        ),
    ]
