# Generated by Django 6.0.4 on 2026-06-08 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titre")),
                ("abstract", models.TextField(verbose_name="Résumé")),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mots-clés"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Format souhaité"
                    ),
                ),
                (
                    "availability",
                    models.TextField(blank=True, verbose_name="Disponibilités"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Soumis"),
                            ("under_review", "En cours d'évaluation"),
                            ("accepted", "Accepté"),
                            ("rejected", "Refusé"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "submitter_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email du soumissionnaire"
                    ),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["committee", "organizer"]},
                        related_name="assigned_proposals",
                        to="events.membership",
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition",
                "verbose_name_plural": "Propositions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "institution",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Institution"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="submissions.proposal",
                        verbose_name="Proposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auteur·ice",
                "verbose_name_plural": "Auteur·ices",
                "ordering": ["order", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("for", "Pour"),
                            ("against", "Contre"),
                            ("hesitant", "Hésitant·e"),
                        ],
                        max_length=10,
                        verbose_name="Avis",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="events.membership",
                        verbose_name="Évaluateur·ice",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="submissions.proposal",
                        verbose_name="Proposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "unique_together": {("proposal", "evaluator")},
            },
        ),
    ]
