# Generated by Django 6.0.4 on 2026-06-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_submission_custom_fields"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Texte d'aide"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Texte court"),
                            ("textarea", "Texte long"),
                            ("choice", "Choix unique"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="Options"),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Obligatoire"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_fields",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ de soumission",
                "verbose_name_plural": "Champs de soumission",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFieldResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Valeur")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="submissions.submissionfield",
                        verbose_name="Champ",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_responses",
                        to="submissions.proposal",
                        verbose_name="Proposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse champ",
                "verbose_name_plural": "Réponses champs",
                "unique_together": {("proposal", "field")},
            },
        ),
    ]
