# Generated by Django 6.0.4 on 2026-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_submission_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio-bibliographie"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="abstract",
            field=models.TextField(verbose_name="Proposition de communication"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="title",
            field=models.CharField(
                max_length=500, verbose_name="Titre de la communication"
            ),
        ),
    ]
