# Generated by Django 6.0.4 on 2026-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_bio_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("confirmed", "Confirmé·e"),
                    ("cancelled", "Annulé·e"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Présence",
            ),
        ),
    ]
