# Generated by Django 6.0.4 on 2026-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_proposal_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfield",
            name="help_text_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Texte d'aide (EN)"
            ),
        ),
        migrations.AddField(
            model_name="submissionfield",
            name="label_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Intitulé (EN)"
            ),
        ),
    ]
