# Generated by Django 6.0.4 on 2026-06-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_bilingual_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Soumis"),
                    ("under_review", "En cours d'évaluation"),
                    ("accepted", "Accepté"),
                    ("rejected", "Refusé"),
                    ("cancelled", "Annulé·e"),
                ],
                default="submitted",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
