# Generated by Django 6.0.4 on 2026-06-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnexEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("date", models.DateField(verbose_name="Jour")),
                ("start_time", models.TimeField(verbose_name="Début")),
                ("end_time", models.TimeField(verbose_name="Fin")),
                ("label", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("break", "Pause"),
                            ("meal", "Repas"),
                            ("plenary", "Plénière"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annex_events",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement annexe",
                "verbose_name_plural": "Événements annexes",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("date", models.DateField(verbose_name="Jour")),
                ("start_time", models.TimeField(verbose_name="Début")),
                ("end_time", models.TimeField(verbose_name="Fin")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Salle / lieu"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Intitulé de la session",
                    ),
                ),
                (
                    "moderator",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modérateur·ice"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["date", "start_time", "order"],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titre")),
                (
                    "speaker_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Intervenant·e"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="Durée (min)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication",
                        to="submissions.proposal",
                        verbose_name="Proposition liée",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="programme.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "ordering": ["order"],
            },
        ),
    ]
