# Generated by Django 6.0.4 on 2026-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programme", "0004_annexevent_cultural"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annexevent",
            options={
                "ordering": ["date", "order", "start_time"],
                "verbose_name": "Événement annexe",
                "verbose_name_plural": "Événements annexes",
            },
        ),
        migrations.AddField(
            model_name="annexevent",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
        ),
    ]
