# Generated by Django 6.0.4 on 2026-06-08 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=False, verbose_name="Ouvert aux réponses"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date limite de réponse"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Instructions pour les intervenants"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_form",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulaire logistique",
                "verbose_name_plural": "Formulaires logistiques",
            },
        ),
        migrations.CreateModel(
            name="LogisticsField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Texte d'aide"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Texte court"),
                            ("textarea", "Texte long"),
                            ("boolean", "Oui / Non"),
                            ("choice", "Choix unique"),
                            ("multichoice", "Choix multiple"),
                            ("date", "Date"),
                            ("time", "Heure"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Pour les types choix : liste des options, une par ligne.",
                        verbose_name="Options",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Obligatoire"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="logistics.logisticsform",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ",
                "verbose_name_plural": "Champs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "respondent_name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'intervenant·e"
                    ),
                ),
                (
                    "respondent_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Réponse complète"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="logistics.logisticsform",
                        verbose_name="Formulaire",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_response",
                        to="submissions.proposal",
                        verbose_name="Proposition liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse logistique",
                "verbose_name_plural": "Réponses logistiques",
                "ordering": ["respondent_name"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsFieldResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Valeur")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_responses",
                        to="logistics.logisticsfield",
                        verbose_name="Champ",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_responses",
                        to="logistics.logisticsresponse",
                        verbose_name="Réponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur de champ",
                "verbose_name_plural": "Valeurs de champs",
                "unique_together": {("response", "field")},
            },
        ),
    ]
