# Generated by Django 6.0.4 on 2026-06-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_public_page_fields"),
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logisticsresponse",
            name="proposal",
        ),
        migrations.AddField(
            model_name="logisticsform",
            name="name",
            field=models.CharField(
                default="Formulaire logistique",
                max_length=255,
                verbose_name="Nom du formulaire",
            ),
        ),
        migrations.AlterField(
            model_name="logisticsform",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logistics_forms",
                to="events.event",
                verbose_name="Événement",
            ),
        ),
        migrations.AlterField(
            model_name="logisticsform",
            name="instructions",
            field=models.TextField(blank=True, verbose_name="Instructions"),
        ),
    ]
