# Generated by Django 6.0.4 on 2026-06-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_public_page_fields"),
        ("logistics", "0003_add_reimbursement"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salle", "Salle"),
                            ("traiteur", "Traiteur"),
                            ("transport", "Transport"),
                            ("communication", "Communication"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "amount_planned",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant prévu (€)",
                    ),
                ),
                (
                    "amount_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant réel (€)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_lines",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste budgétaire",
                "verbose_name_plural": "Postes budgétaires",
                "ordering": ["category", "label"],
            },
        ),
        migrations.CreateModel(
            name="BudgetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("devis", "Devis"),
                            ("facture", "Facture"),
                            ("bon_de_commande", "Bon de commande"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("file", models.FileField(upload_to="budget/", verbose_name="Fichier")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant (€)",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="logistics.budgetline",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document budgétaire",
                "verbose_name_plural": "Documents budgétaires",
            },
        ),
    ]
