# Generated by Django 6.0.4 on 2026-06-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_public_page_fields"),
        ("logistics", "0004_add_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "envelope",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget global alloué à l'événement.",
                        max_digits=10,
                        null=True,
                        verbose_name="Enveloppe totale (€)",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_settings",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres budget",
                "verbose_name_plural": "Paramètres budget",
            },
        ),
    ]
