# Generated by Django 6.0.4 on 2026-06-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_add_budget_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="category",
            field=models.CharField(
                choices=[
                    ("salle", "Salle"),
                    ("traiteur", "Traiteur"),
                    ("restaurant", "Restaurant"),
                    ("boissons", "Boissons"),
                    ("cafe", "Pauses café"),
                    ("transport", "Transport"),
                    ("communication", "Communication"),
                    ("autre", "Autre"),
                ],
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
    ]
