# Generated by Django 6.0.4 on 2026-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0007_budget_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetcharge",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="budgetcharge",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Supprimé le"
            ),
        ),
        migrations.AlterField(
            model_name="budgetcharge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
    ]
