# Generated by Django 6.0.4 on 2026-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0008_alter_budgetcharge_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsfield",
            name="help_text_en",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Texte d'aide (EN)"
            ),
        ),
        migrations.AddField(
            model_name="logisticsfield",
            name="label_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Intitulé (EN)"
            ),
        ),
        migrations.AddField(
            model_name="logisticsform",
            name="instructions_en",
            field=models.TextField(blank=True, verbose_name="Instructions (EN)"),
        ),
        migrations.AddField(
            model_name="logisticsform",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom du formulaire (EN)"
            ),
        ),
    ]
