# Generated by Django 6.0.4 on 2026-06-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Objet")),
                ("body", models.TextField(verbose_name="Corps du message")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_members", "Tous les membres"),
                            ("speakers", "Intervenants uniquement"),
                            ("accepted", "Propositions acceptées (soumettants)"),
                            ("committee", "Comité scientifique"),
                        ],
                        max_length=20,
                        verbose_name="Destinataires",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Envoyé le"
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre envoyé"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_campaigns",
                        to="events.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne email",
                "verbose_name_plural": "Campagnes email",
                "ordering": ["-created_at"],
            },
        ),
    ]
