# Generated by Django 6.0.4 on 2026-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_new_submission_notification_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("submission_confirmation", "Confirmation de soumission"),
                    ("submission_token_reminder", "Renvoi du lien de suivi"),
                    (
                        "new_submission_notification",
                        "Notification organisateur — nouvelle soumission",
                    ),
                    ("member_invitation", "Invitation d'un membre"),
                    ("committee_invitation", "Invitation comité scientifique"),
                    ("logistics_email_link", "Lien formulaire logistique"),
                ],
                max_length=100,
                unique=True,
                verbose_name="Identifiant",
            ),
        ),
    ]
